server:
  port: 7004
spring:
  application:
    name: xll-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
#    hostname: zuul7004.com
zuul:
  prefix: /api # 添加路由前缀
  routes: #配置路由规则
    item-service: /item/**
    ignored-services:
    - upload-service # 忽略upload-service服务

ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  OkToRetryOnAllOperations: false # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：10000ms