server:
  port: 8001
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://192.168.10.150:3306/xll_study?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

  instance:
    prefer-ip-address: true
#    hostname: xll.service.com
#    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
#打印sql语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
